version: '3'

services:
        db:
                image: postgres:latest
                volumes:
                        - postgres_data:/var/lib/postgresql/data
                environment:
                        POSTGRES_PASSWORD: $DB_PASSWORD
                env_file:
                        - .env
        web:
                restart: always
                build: .
                command: >
                        bash -c "python ./bash/start.py
                        && ./bash/start.sh"
                volumes:
                        - .:/TestTask
                ports:
                        - "80:8888"
                env_file:
                        - .env
                depends_on:
                        - db
volumes:
        postgres_data:
